version: '3.8'
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - ./backend:/app
        env_file:
            - ./backend/.env

    mysql_db:
        image: mysql
        platform: linux/x86_64
        environment:
            MYSQL_DATABASE: 'studio'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'pass'
            MYSQL_ROOT_PASSWORD: 'pass'
        ports:
            - '3306:3306'
        expose:
            - 3306
        volumes:
            - ./data:/var/lib/mysql
