export default [
    {
        type: 'move_down',
        lastDummyAlign0: 'CENTRE',
        message0: 'Down',
        previousStatement: null,
        nextStatement: null,
        colour: 120,
        tooltip: 'move the sprite down',
        helpUrl: '',
    },
    {
        type: 'move_up',
        lastDummyAlign0: 'CENTRE',
        message0: 'Up',
        previousStatement: null,
        nextStatement: null,
        colour: 120,
        tooltip: 'move the sprite down',
        helpUrl: '',
    },
    {
        type: 'move_left',
        lastDummyAlign0: 'CENTRE',
        message0: 'Left',
        previousStatement: null,
        nextStatement: null,
        colour: 120,
        tooltip: 'move the sprite down',
        helpUrl: '',
    },
    {
        type: 'move_right',
        lastDummyAlign0: 'CENTRE',
        message0: 'Right',
        previousStatement: null,
        nextStatement: null,
        colour: 120,
        tooltip: 'move the sprite down',
        helpUrl: '',
    },
];
